[package]
name = "ghostpay"
version = "0.1.0"
edition = "2024.beta"
published-at = "0x55aa16798f8258b5297c96ec083d6f1e2ac15a64d2398db9758012406a3170bd"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
ghostpay = "0x55aa16798f8258b5297c96ec083d6f1e2ac15a64d2398db9758012406a3170bd"
